[package]
name = "git_tui_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
env_logger = "0.11"
git2 = "0.19"
log = "0.4"
simplelog = "0.12"
ratatui = "0.28"
tokio = { version = "1", features = ["full"] }
